// Category tile art — generated by scripts/gen_category_art.cjs and looked up by category name. Falls back
// to the designed branded tile when a category has no art yet.
import manifest from '@/public/catalog-art-manifest.json';
export const artFor = (name) => (name && manifest[name]) || null;
